### PR TITLE
Better dev environment (parcel, prod/dev .env files)

### PR DESCRIPTION
**Pull request by oveddan**
Improvements to dev environment/easier setup.

I have not fully tested this, nor should it be deployed to production before it is properly tested.  Just opening this hear for a review.

* Using parcel bundler for js build.  This allows for live reloading, and less configuration (and some other bundlers we can use in the future).  It also allows for grabbing variables from .env files.
* Moved .env filed to .env.development and .env.production, and removing those from config.js, so that they can be switched between environments
* Moved some configuration from config.js to the .env files, so that we don't need to comment things out. when deploying/running locally
* Using node-dot-env to start node with a specific .env file
* Using npm-run-all to run a bunch of files at the same time
* Added some instructions to the readme to get started.
* If https is not available, listen using http in node.  This allows someone spinning up the project to get things off the ground easily.
* Share server host and port config using .env files between server and client, so that they are synchronized.
* Using parcel to build production bundle.
* moved server.js to server/index.js, so that we can eventually break this up into smaller functionality
* moved babel config to .babelrc file
* In dev, proxy static asset requests to the express server
* adding instructions for generating certs without needing a prompt

### CODE REVIEW

**Comment by AidanNelson** [comment]
Hi Dan,

These changes look like they will make this project much easier to get up and running.  I think in particular having the two separate .env files will help make things a lot easier.  Very exciting!  

A couple thoughts:
* I think maintaining compatibility with **npm** in both the build system and documentation would be valuable for whoever prefers not to install **yarn** or wants to get up and running with one fewer steps.  Maybe we could list both sets of instructions in the documentation?  Or do you think this would be more work than is necessary down the line?
* We have the beginnings of a local build documentation [here](https://github.com/AidanNelson/YORB2020/blob/main/docs/CONTRIBUTING.md).  Could you move the build instructions there?

Also, I am running this locally (with **npm** rather than **yarn**), and am seeing the following two errors:
* Server not seeing certs (because it is running without HTTPS by default in development mode?):
```
demo-app:ERROR could not start https server TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.openSync (fs.js:431:3)
    at Object.readFileSync (fs.js:344:35)
    at main (/Users/aidannelson/Desktop/YORB2020/YORB2020/server/index.js:193:16)
    at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
```
* Also, the build is failing:
```
 Build failed.
Error: Unknown version 81 of edge
BrowserslistError: Unknown version 81 of edge
    at Function.select (/Users/aidannelson/Desktop/YORB2020/YORB2020/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:1086:17)
    at /Users/aidannelson/Desktop/YORB2020/YORB2020/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:336:33
    at Array.reduce (<anonymous>)
    at resolve (/Users/aidannelson/Desktop/YORB2020/YORB2020/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:318:18)
    at browserslist (/Users/aidannelson/Desktop/YORB2020/YORB2020/node_modules/@babel/helper-compilation-targets/node_modules/browserslist/index.js:443:21)
    at getTargets (/Users/aidannelson/Desktop/YORB2020/YORB2020/node_modules/@babel/helper-compilation-targets/lib/index.js:202:48)
    at _default (/Users/aidannelson/Desktop/YORB2020/YORB2020/node_modules/@babel/preset-env/lib/index.js:246:57)
    at /Users/aidannelson/Desktop/YORB2020/YORB2020/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at getNeededPlugins (/Users/aidannelson/Desktop/YORB2020/YORB2020/node_modules/@parcel/transformer-babel/lib/env.js:47:33)
    at shouldCompileFurther (/Users/aidannelson/Desktop/YORB2020/YORB2020/node_modules/@parcel/transformer-babel/lib/env.js:55:31)
```

**Comment by oveddan** [comment]
Yeah I think adding npm instructions makes sense.

Didn't know about the build documentation, will move it there.

We can do all changes in a separate branch for now.

**Comment by oveddan** [comment]
I was actually thinking - i didnt know this contributing guide exists.  Most repositories have on the main readme instructions for running the repo locally, so i think it makes sense for that to be on the main readme.

What do you think of just having a contributing section in the main readme, and moving all the contents from here onto there?

**Comment by oveddan** [comment]
I did an update that moved the setup instructions all to the main readme....i think thats where it belongs as it makes those instructions easily accessible/clearly findable.

Regarding the build issue - I can't reproduce on my end.

Maybe try removing the node_modules folder and re-installing packages and trying again?

**Comment by oveddan** [comment]
I can run with npm start without a problem:
Screen Shot 2020-07-07 at 11 24 03 AM

Maybe something to do with .env files not sure

**Comment by oveddan** [comment]
Figured out what the issue with loading certs was; had to load it from the root of the repo.  Fixed in latest commit.

Still tbd how to do proper https with both the client AND server on dev

**Comment by oveddan** [comment]
Ok @AidanNelson with latest changes, https should work now.  Check out the updated readme.

To start with https run:

`yarn start-https` or `npm run start-https`

Check out updated instructions on how to setup the environment config file for https, and sign a cert (new instructions dont require user to enter anything in the prompts)

The disadvantage of https is you dont get live reloading of client side code.

**Comment by AidanNelson** [comment]
Hmmmm... I tried deleting the node_modules folder and reinstalling using npm install and am still getting a build error when trying to run with `npm start` and when running with `npm run start-https.`  In both cases, the server starts correctly, but the client side code fails to build.  
```
 demo-app http server listening on port 3000 +30ms
🚨  Build Error
/YORB2020/public/images/favicon.png: Unknown version 68 of opera
```
One possible clue: the favicon somehow is no longer the YORB icon, but the thesis 2020 icon:

Screen Shot 2020-07-08 at 10 22 51 AM

**Comment by AidanNelson** [comment]
Update: I (sort of) followed the solution [shown here](https://github.com/ng-packagr/ng-packagr/issues/1411#issuecomment-537205616) to fix the build.  Basically I deleted package.json and node_modules, then ran `npm install` again.  I guess I had something wrong in my package.json that was being reinstalled when I ran `npm install` before...  Good news is no one else should run into this.

**Comment by oveddan** [comment]
Great!!! do you still have favicon issues?

**Comment by AidanNelson** [comment]
No, no favicon issues anymore!

**Pull request merged**
